Repository SAP/devops-docker-images, pull requests merged in 2019-02, with the labels that each got.

#22 Doc: Fix backtics in bash example in markdown
  mta-archive-builder/README.md
Labels: documentation

#23 [Doc] Fixing Links and describe more details
  README.md
Labels: documentation

#21 Automated test of infrastructure
  .gitignore
  .travis.yml
  cx-server-companion/.gitignore
  cx-server-companion/files/cx-server-companion.sh
  cx-server-companion/life-cycle-scripts/cx-server
  infrastructure-tests/Jenkinsfile
  infrastructure-tests/README.md
  infrastructure-tests/jenkins.yml
  infrastructure-tests/pipeline_config.yml
  infrastructure-tests/runTests.sh
  infrastructure-tests/testing-jenkins.yml
Labels: review

#32 [documentation] adapt node-rfc link
  README.md
Labels: documentation, review
