Repository SAP/devops-docker-images, pull requests merged in 2019-06, with the labels that each got.

#79 fix link to docker hub
  mta-archive-builder/README.md
Labels: merge

#103 Add document about self signed tls closes #102
  docs/operations/self-signed-tls.md
Labels: merge

#77 fix hadolint issues for cm-client
  cm-client/Dockerfile
Labels: CM, merge

#105 fix HaDoLint findings in MTA image
  mta-archive-builder/Dockerfile
Labels: MTA

#74 fix linting for mta docker image
  .travis.yml
Labels: MTA, merge
